### ISSUE TITLE
no getUnixTimeSec function

### ISSUE THREAD

**Issue by tonydeck0506** [jkinfeng/DBWnl#1]
when due  "node db3.js" , I found that there is no getUnixTimeSec() function which cause the failure of js execution. It seems that you forgot to the this part of code in the db3.js on getUnixTimeSec.
hope you can fix the issue.
thanks.
Tony

**Comment by tonydeck0506** [comment]
the whole error message is as follows.
let a3 = new Date(a2).getUnixTimeSec();
                          ^

TypeError: (intermediate value).getUnixTimeSec is not a function
    at getJieQi (/Users/tonydeck/Downloads/dash-3/jupyter/githubAdvisor/yiAdvisor/sqllite3/db3.js:78:27)
    at Object.<anonymous> (/Users/tonydeck/Downloads/dash-3/jupyter/githubAdvisor/yiAdvisor/sqllite3/db3.js:51:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by tonydeck0506** [comment]
I'm using the stuff in my macOS system

**Comment by tonydeck0506** [comment]
I have found the root cause. the following "require" is not correct. I think it is caused by the .
"require('datetime-helper');" which the getUnixTimeSec() is in it .
I've updated db3.js . I did the correct "require" and invoke the correct one.
I start a pull request on db3.js
thanks.
Tony

**Comment by jkinfeng** [comment]
> when due "node db3.js" , I found that there is no getUnixTimeSec() function which cause the failure of js execution. It seems that you forgot to the this part of code in the db3.js on getUnixTimeSec. hope you can fix the issue. thanks. Tony

install node.js from https://www.nodejs.org
please run in console: npm i 
or
to website download the code https://www.npmjs.com/package/datetime-helper
